[package]
name = "bento_ui"
description = ""
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bento_macros = { workspace = true }
bento_wgpu = { workspace = true }

tokio = { workspace = true, features = ["time"] }
cosmic-text = { workspace = true }
