[package]
name = "bento_ui"
description = ""
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bento_macros = { workspace = true }
bento_wgpu = { workspace = true }

cosmic-text = { workspace = true }
web-time = { workspace = true }
slab = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["time"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true }
web-sys = { workspace = true, features = ["Window"] }
wasm-bindgen-futures = { workspace = true }
