[package]
name = "bento"
version = "0.5.3"
edition = "2024"

[dependencies]
wgpu = "25"
bytemuck = { version = "1.14", features = ["derive"] }
winit = "0.30"
pollster = "0.3"
tokio = { version = "1", features = ["full"] }
taffy = "0.9.2"
cosmic-text = "0.18"
image = "0.25"
resvg = "0.44"

bento_derive = { path = "../bento_derive" }
bento_wgpu = { path = "../bento_wgpu" }

[dev-dependencies]
winit = "0.30"
pollster = "0.3"
