[package]
name = "bento_wgpu"
description = "wgpu-based renderer for Bento"
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bento_shared = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
cosmic-text = { workspace = true, features = ["shape-run-cache"] }
swash = { workspace = true }
etagere = { workspace = true }
image = { workspace = true }
resvg = { workspace = true }
slab = { workspace = true }

[dev-dependencies]
winit = { workspace = true }
pollster = { workspace = true }
