[workspace]
members = [
  "crates/bento",
  "crates/bento_macros",
  "crates/bento_shared",
  "crates/bento_winit",
  "crates/bento_wgpu",
  "crates/bento_ui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/oganas/bento"
keywords = ["gui", "ui", "graphics", "wgpu"]
categories = ["gui", "graphics", "rendering"]

[workspace.dependencies]
bento = { path = "crates/bento" }
bento_macros = { path = "crates/bento_macros" }
bento_ui = { path = "crates/bento_ui" }
bento_shared = { path = "crates/bento_shared" }
bento_wgpu = { path = "crates/bento_wgpu" }
bento_winit = { path = "crates/bento_winit" }

wgpu = "25"
bytemuck = { version = "1.14", features = ["derive"] }
etagere = "0.2"
swash = "0.2"
cosmic-text = "0.18"
image = "0.25"
resvg = "0.44"
winit = "0.30"
pollster = "0.3"
tokio = { version = "1", features = ["full"] }
slab = "0.4"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
type-complexity = "allow"
large-enum-variant = "allow"
semicolon_if_nothing_returned = "deny"
trivially-copy-pass-by-ref = "deny"
default_trait_access = "deny"
redundant-closure-for-method-calls = "deny"
manual_let_else = "deny"
unused_async = "deny"
needless_borrow = "deny"
new_without_default = "deny"
useless_conversion = "deny"

[workspace.lints.rustdoc]
broken_intra_doc_links = "forbid"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
# opt-level = 3
# lto = "thin"
# codegen-units = 1
# strip = "symbols"

[profile.release-debug]
inherits = "release"
strip = "none"
debug = true
