[package]
name = "bento_winit"
description = "winit-based windowing and app lifecycle for Bento"
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bento_shared = { workspace = true }
bento_wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
cosmic-text  = { workspace = true }
