use crate::element::layout::Layout;
use crate::element::values::*;

pub struct Base {
    pub layout: Layout,
    pub dirty: bool,
}

impl Base {
    pub fn new() -> Self {
        Self {
            layout: Layout::default(),
            dirty: true,
        }
    }

    pub fn layout(&self) -> &Layout {
        &self.layout
    }
    pub fn layout_mut(&mut self) -> &mut Layout {
        &mut self.layout
    }
    pub fn layout_mut_dirty(&mut self) -> &mut Layout {
        self.dirty = true;
        &mut self.layout
    }
    pub fn is_dirty(&self) -> bool {
        self.dirty
    }
    pub fn set_dirty(&mut self, v: bool) {
        self.dirty = v;
    }
}

// HasBase 
// generated by #[derive(Element)] 
// user wont never write this manually

pub trait HasBase {
    fn base(&self) -> &Base;
    fn base_mut(&mut self) -> &mut Base;
}

// ayout setters 
// blanket impl: any type with hasbase gets all layout setters for free
// all setters mark dirty automatically

pub trait LayoutExt: HasBase + Sized {
    fn set_width(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().width = v;
        self
    }
    fn set_height(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().height = v;
        self
    }
    fn set_min_w(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().min_w = v;
        self
    }
    fn set_max_w(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().max_w = v;
        self
    }
    fn set_min_h(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().min_h = v;
        self
    }
    fn set_max_h(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().max_h = v;
        self
    }
    fn set_padding(&mut self, v: [f32; 4]) -> &mut Self {
        self.base_mut().layout_mut_dirty().padding = v;
        self
    }
    fn set_margin(&mut self, v: [f32; 4]) -> &mut Self {
        self.base_mut().layout_mut_dirty().margin = v;
        self
    }
    fn set_row_gap(&mut self, v: f32) -> &mut Self {
        self.base_mut().layout_mut_dirty().row_gap = v;
        self
    }
    fn set_col_gap(&mut self, v: f32) -> &mut Self {
        self.base_mut().layout_mut_dirty().col_gap = v;
        self
    }
    fn set_flex_direction(&mut self, v: FlexDirection) -> &mut Self {
        self.base_mut().layout_mut_dirty().flex_direction = v;
        self
    }
    fn set_flex_wrap(&mut self, v: FlexWrap) -> &mut Self {
        self.base_mut().layout_mut_dirty().flex_wrap = v;
        self
    }
    fn set_flex_grow(&mut self, v: f32) -> &mut Self {
        self.base_mut().layout_mut_dirty().flex_grow = v;
        self
    }
    fn set_flex_shrink(&mut self, v: f32) -> &mut Self {
        self.base_mut().layout_mut_dirty().flex_shrink = v;
        self
    }
    fn set_flex_basis(&mut self, v: Size) -> &mut Self {
        self.base_mut().layout_mut_dirty().flex_basis = v;
        self
    }
    fn set_align_items(&mut self, v: AlignItems) -> &mut Self {
        self.base_mut().layout_mut_dirty().align_items = v;
        self
    }
    fn set_align_self(&mut self, v: AlignSelf) -> &mut Self {
        self.base_mut().layout_mut_dirty().align_self = v;
        self
    }
    fn set_justify_content(&mut self, v: JustifyContent) -> &mut Self {
        self.base_mut().layout_mut_dirty().justify_content = v;
        self
    }
    fn set_position(&mut self, v: Position) -> &mut Self {
        self.base_mut().layout_mut_dirty().position = v;
        self
    }
    fn set_inset(&mut self, v: [Size; 4]) -> &mut Self {
        self.base_mut().layout_mut_dirty().inset = v;
        self
    }
    fn set_overflow_x(&mut self, v: Overflow) -> &mut Self {
        self.base_mut().layout_mut_dirty().overflow_x = v;
        self
    }
    fn set_overflow_y(&mut self, v: Overflow) -> &mut Self {
        self.base_mut().layout_mut_dirty().overflow_y = v;
        self
    }
    fn set_z_index(&mut self, v: i32) -> &mut Self {
        self.base_mut().layout_mut_dirty().z_index = v;
        self
    }
    fn set_opacity(&mut self, v: f32) -> &mut Self {
        self.base_mut().layout_mut_dirty().opacity = v;
        self
    }
    fn set_visible(&mut self, v: bool) -> &mut Self {
        self.base_mut().layout_mut_dirty().visible = v;
        self
    }
    fn set_aspect_ratio(&mut self, v: Option<f32>) -> &mut Self {
        self.base_mut().layout_mut_dirty().aspect_ratio = v;
        self
    }
}

// every type with HasBase automatically gets all layout setters
impl<T: HasBase> LayoutExt for T {}
