[package]
name = "bento"
description = "Rust GUI framework"
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
bento_ui = { workspace = true }
bento_winit = { workspace = true }
